### ISSUE TITLE
Error on Ubuntu 16.04

### ISSUE THREAD

**Issue by boubounokefalos** [leaty/camctl#2]
After the installation, when I try to type 
`sudo camctl --help
`
I get the following error:

`Traceback (most recent call last):
  File "/usr/bin/camctl", line 3, in <module>
    import usb.core
ImportError: No module named 'usb'
`
Any ideas? :D

**Comment by leaty** [comment]
Hey!

Seems like the usb lib is missing, try `sudo pip3 install pyusb`.

**Comment by boubounokefalos** [comment]
Thank you very much indeed it worked! If you are interested in adding led and/or extended functionality count me in as a tester. I own an x52 (same usb ID as x62).

Thanks again!

**Comment by leaty** [comment]
No worries! For me personally, the only thing missing is thermals and speed monitoring. However, I'll gladly and quite easily add any other suggested functionality if the hex codes are provided to me.

This can be done by running CAM on Windows and monitoring the USB cap with Wireshark. I am looking for `Leftover Capture Data`. You can email me at dev@leaty.net.
