### ISSUE TITLE
Does it will be work on macOS/bsd?

### ISSUE THREAD

**Issue by serhiicherepanov** [leaty/camctl#6]
Hi, thanks for your tool!

I want to build a hack and use the nzxt cooler.

Does it will be work? Otherwise I will check it soon.

**Comment by leaty** [comment]
Sorry, didn't notice your issue. Anyway theoretically it should work, you may want to recheck vid and pid on line 39 to make sure it matches your cooler. I do not own a nzxt cooler anymore so I am unable to test.
