### ISSUE TITLE
Depencency missing: cam

### ISSUE THREAD

**Issue by brean** [leaty/camctl#7]
Using Ubuntu 20.04 I am missing cam as dependency:

```
Traceback (most recent call last):
  File "/usr/bin/camctl", line 56, in <module>
    cam = CAM(vid, pid)
  File "/usr/bin/camctl", line 12, in __init__
    self._find()
  File "/usr/bin/camctl", line 16, in _find
    self.device = devices[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/camctl", line 64, in <module>
    cam.declaim()
NameError: name 'cam' is not defined
```

a `sudo python3 -m pip install cam` does not seem to install the right cam/does not solve the issue. What is cam?

**Comment by leaty** [comment]
CAM is just a class name in this repo, it's not a dependency.
https://github.com/leaty/camctl/blob/ad80f8a9d3263a33a90692c05a3e6a19aecede82/camctl#L8

The error you are getting refers to line 16:
https://github.com/leaty/camctl/blob/ad80f8a9d3263a33a90692c05a3e6a19aecede82/camctl#L16

Which most likely means these defaults are incorrect for you, try the command in the comment and find yours:
https://github.com/leaty/camctl/blob/ad80f8a9d3263a33a90692c05a3e6a19aecede82/camctl#L37-L40

**Comment by brean** [comment]
Yes, my pid is different:
Bus 003 Device 004: ID 1e71:2007 NZXT
